### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by Your-Name-Here** [uilicious/english-compiler#2]
I wanted to do something like this if it hasnt been done before. This is how I found this repo. 

I was reading through the code and wanted to ask why you chose some of the core design decisions. 

Why markdown files?
It would seem to me at least that writing specs would be more efficient or standardized if done with JSON or YAML or even Toml.  YAML is cheaper to parse with openAI. 

compiler.config.yaml
```yaml
language: typescript
project_tree_dir: c://...
memory_scratch_pad_dir: c://...
prefer_classes: true
prefer_function: true
max_api_calls_per_file: 10
api_key: sk-xxxxxxxxxxxxxxxxxxxx
```
DatabaseController.spec.yaml
```yaml
test: true
linked_modules:
  - feature1
  - feature2
description: This widget will control the SQL database
required_functionality:
  - name: getRows
    description: 'Performs a query on a table,'
    args:
      - table: string
      - query: string
    returns: bool
  - name: addRows
    description: 'Adds a row to a table,'
    args:
      - table: string
      - query: string
    returns: bool
...and so on
```

Additionally, there seems to be a large focus on reducing calls to the API. I understand that it costs for every call you send. However, I can't imagine that this would cost more than a few cents per file. So even with a larger codebase being generated, you'd be looking at a few USD at most. This could jump-start your project and save you hundreds of man-hours for just a couple of dollars. If it is too expensive for some, they have the option to code everything by hand including tests and documentation. 

When sending a request to generate a function/method, you also include a file tree with schemas like above, for all other methods only if the file size is larger than the context window. Otherwise, send the whole file with the request to generate method x from the schema.
